### ISSUE TITLE
Focus-Bug with multiple Textareas

### ISSUE THREAD

**Issue by CoreKnowledge** [mohan/tinymce-placeholder#3] opened 2015-09-17 09:23 UTC
Hey,
for me the problem occured, that if I use the placeholder plugin for more than one tinymce textarea, there is a bug with the focus of the cursor.
So if I click in the first tinymce editor, the focus jumps to the second (both placeholder texts dissappear). If I go to a field without a tinymce editor and reselect on of the editors, behaviour is kind of random, if the focus is set to the correct or the wrong one.
Best regards!

**Comment by effectjared** [comment] 2015-11-06 09:37
I also have this problem which seems to be caused by the label not actually being part of the editor itself. If you click in the textarea but not on the placeholder it works as normal.

A fix for this is to add the `pointer-events: none` style to the placeholder on line 32

`attrs = {style: {position: 'absolute', top:'5px', left:0, color: '#888', padding: '1%', width:'98%', overflow: 'hidden', 'pointer-events': 'none'} };`

The downside to this is that it doesn't work on IE10 and below.

Another workaround would be to comment out line 7, which would cause clicking the placeholder to not work at all, so it's not really recommended

`tinymce.DOM.bind(label.el, 'click', onFocus);`

**Comment by luchorengo** [comment] 2016-02-16 06:13
great work @effectjared, works perfect!

**Comment by AfzalH** [comment] 2016-05-24 06:20
a better fix.
replace 
`tinyMCE.execCommand('mceFocus', false, editor);`
with
`editor.execCommand('mceFocus', false);`

**Closed** 2016-06-05 14:56 UTC
